runtime: nodejs16  # or your Node.js version
instance_class: F2
env_variables:
  PORT: 3001
  MONGODB_URI: 'mongodb+srv://anas:wlGkxnbPXfCPMxbo@cluster0.gshstz2.mongodb.net/test'
  JWT_SECRET: 'your_secret_key'
  OPENAI_ORGANIZATION: 'org-L9YHbc4YsSjFizpGJ6Lcw54q'
  OPENAI_API_KEY: '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'
  NODE_ENV: 'development'